remote_theme: sharu725/online-cv
title: Dmitry Baranov - Senior Backend Developer (PHP, Go) - CV
url: 'http://baranov.in/'
description: |
  Personal Web CV of Dmitry Baranov - Senior Backend Developer (PHP, Go).
  I have a huge experience developing complex PHP applications using Symfony framework.
  Key skills: PHP, Go, Symfony, MySQL, PostgreSQL, ElasticSearch, RabbitMQ, Redis, Docker,
  Linux, Networks.
theme_skin: ceramic

sass:
  sass_dir: _sass
  style: compressed

compress-site: yes

encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development
